workflows

diff --git a/.github/workflows/nix-build.yml b/.github/workflows/nix-build.yml
--- a/.github/workflows/nix-build.yml
+++ b/.github/workflows/nix-build.yml
@@ -26,3 +26,10 @@ jobs:
 
       - name: Build GLF
         run: nix run github:Mic92/nix-fast-build -- --no-nom  --skip-cached --systems 'x86_64-linux' -f .#nixosConfigurations.glf-installer.config.system.build.toplevel 
+
+      - name: Validate Build
+        run: |
+          if [ ! -d result ]; then
+          echo "Build failed! Check logs for details."
+          exit 1
+          fi
